# 2.0 Rudimenti sulla libreria Numpy

In questo capitolo, l'obiettivo principale sarà quello di introdurre alcune operazioni base per le matrici, per l'esposizione cercheremo di trattare vettori e matrici nel modo più intuitivo possibile. In particolare possiamo iniziare a notare __isomorfismo__ tra vettori e matrici. I vettori infatti non sono altro che collezioni di coefficienti $ a_1,\dots,a_n $, e a loro volta le matrici non sono altro che collezioni di vettori. Ogni matrice infatti può essere rappresentata come un lungo vettore:

__Prop__:_Sia $A$ una matrice $m \times n$ appartenente allo spazio vettoriale $\mathbb{R}^{m \times n}$. Questa matrice può essere rappresentata come un vettore ad m componenti (numero di righe) seguito da n vettori (numero di colonne) della stessa lunghezza del primo. E appartenente allo spazio vettoriale $\mathbb{R}^{mn}$_

In particolare questa operazione sarà fondamentale successivamente, in quanto ci consente di eseguire un __re-shape__ della matrice. Segue un esempio:


In [1]:
import numpy as np
"""  per dichiarare un array basta definire una concatenazione di liste e virgole, 
tutto questo è più intuitivo con un esempio """ 

A = np.array([[1, 2, 3],
             [4, 5, 6]])
"""ovviamente molti dei metodi classici valgono anche per gli array di numpy, come ad
esempio la print, oppure l'indicizzazione delle liste""" 

print(A)

for entries in A:
    print (entries)

"""il numero di indici, essendo una mxn è 2, il primo individua 
   la riga e il secondo la colonna, da notare come gli indici delle liste sono
   del tutto simili alla gestione delle liste in python"""
    
print(A[0][2])  
"""inoltre ci sono delle funzioni particolari per gli array, ad esempio"""

print(A.shape)

"""oppure quella di cui parlavamo prima, il reshape, dove in questo caso creiamo un vettore
che ha come numero di righe il prodotto di mxn della matrice originale, ovviamente senza 
alcuna colonna"""

B = A.reshape(6,)
print(B)

"""ovviamente numpy offre degli strumenti anche per calcolare la trasposta di una matrice"""

C = A.T
D = A.transpose()

print(C,D)


[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
3
(2, 3)
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]] [[1 4]
 [2 5]
 [3 6]]


Possiamo passare ora alle operazioni tra matrici. Possiamo facilmente individuare due operazioni fondamentali: __somma__ e __moltiplicazione__. Come abbiamo visto in precedenza, per un vettore è abbastanza semplice ed intuitivo applicare queste proprietà:

In [ ]:
"""Come è possibile notare, con i tipi di numpy, è molto più naturale fare delle operazioni
sulle strutture dati, questo perchè sono pensate proprio per soddisfare le proprietà matematiche
dei vettori"""
A = np.array([1,2,3])

A = 3 * A

B = np.array([2,4,6])

print(A,"\n", B,"\n", A+B)

Per le operazioni tra matrici il discorso è diverso, ne diamo brevemente una spiegazione:

1. __Somma di matrici__: La somma di due matrici $A$ e $B$ dello stesso ordine (stesso numero di righe e colonne) si ottiene sommando elemento per elemento:

$$ C=A+B \ \text{con} \ c_{ij} = a_{ij}+b_{ij}$$
Ogni elemento della matrice risultante $C$ è dato dalla somma dei corrispondenti elementi di $A$ e $B$. 

2. __Moltiplicazione di matrici (Inner Product)__: Il prodotto tra matrici $A$ e $B$ è definito quando il numero di colonne di $A$ coincide con il numero di righe di $B$. Si calcola come prodotto scalare tra righe di $A$ e colonne di $B$:

$$C=A⋅B \ \text{con} \ c_{ij}=∑a_{ik}b_{kj}$$

In altre parole, ogni elemento $c{ij}$ della matrice risultante $C$ è la somma dei prodotti degli elementi della riga $i$ di $A$ con quelli della colonna $j$ di $B$.

3. __Hadamard Product (Prodotto elemento per elemento)__: Il prodotto di Hadamard di due matrici 
$A$ e $B$ dello stesso ordine consiste nel moltiplicare elemento per elemento le due matrici:

$$C=A∘B \ \text{con} \ c_{ij}=a_{ij}⋅b_{ij}$$

Ogni elemento della matrice risultante $C$ è quindi il prodotto dei corrispondenti elementi di $A$ e $B$.

Anche in questo caso le operazioni tra matrici sono molto semplici da utilizzare vediamo come farlo 

In [ ]:
A = np.array([[1,2,3],
             [2,3,4]])

"""questa funzione permette di creare degli array di uno, prende diversi parametri,
il primo è una tupla che sta ad indicare la shape della matrice e il secondo, 
dtype=tipo_desiderato"""

B = np.ones((2,3),dtype = "int") 

"""lo stesso vale per la seguente funzione, ma con tutti 0"""

C = np.zeros((2,3),dtype = "int")

print(A, "\n", B, "\n",C)

""" a questo punto possiamo provare le operazioni"""

#--------- SOMMA DI MATRICI 
D = A+B 
print(D) #da notare come i due sistemi debbano essere compatibili 

print("--------------")

#--------- INNER PRODUCT 
""" i seguenti sono due metodi equivalenti per performare l'inner product, l'importante
è che i due sistemi siano compatibili, cioè il numero di righe della prima matrice deve essere
uguale al numero di colonne della seconda
"""
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7,8],
             [9,10],
             [10,11]])

print (A, "\n", B)

H = np.dot(A,B)
C = A @ B
print(A)
print("le due matrici:\n", H, "\n", C, "\nsono identiche")

print("--------------")

#--------- HADAMARD PRODUCT
"""anche in questo caso i due sistemi devono essere compatibili, cioè la loro forma deve
essere uguale"""
A = A.T
C = A * B

print(C)

Questo è quello che serve sapere per iniziare a trattare delle matrici su Python, successivamente vedremo come implementare degli argomenti avanzati dell'__algebra lineare__

### Esercizio 1

Crea una matrice 4x3 con valori da 1 a 12 e svolgi le seguenti operazioni:
* Calcola la trasposta della matrice
* Estrai la seconda colonna
* Estrai la seconda riga
* Reshapa la matrice in un vettore riga di 12 elementi
* Reshapa la matrice in una matrice 2x6

In [ ]:
"""inserire il corpo dell'esercizio"""

### Esercizio 2

Date le matrici:

```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]]) 
v = np.array([2, 3])
```
Calcola:

* Prodotto matriciale tra A e B (A @ B)

* Prodotto di Hadamard (element-wise) tra A e B (A * B)

* Prodotto tra A e v (broadcasting)

* Prodotto tra v e A (broadcasting)

In [ ]:
"""inserire il corpo dell'esercizio"""

### Esercizio 3

Data la matrice:


```python
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

Esegui queste operazioni:

* Calcola la somma di tutti gli elementi della matrice
* Calcola la somma lungo le righe (axis=1) e lungo le colonne (axis=0)
* Trova il valore massimo e la sua posizione (usando np.max() e np.argmax())
* Crea una matrice booleana dove gli elementi sono maggiori di 5

In [ ]:
"""inserire il corpo dell'esercizio"""

### Esercizio 4

Scrivi una funzione che:

* Prende in input una matrice A qualsiasi
* Calcola il prodotto matriciale tra A e la sua trasposta
* Calcola la media di ogni colonna della matrice risultante
* Restituisce il valore massimo tra queste medie

In [ ]:
"""inserire il corpo dell'esercizio"""